# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lawgenesis.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
import google.protobuf
major, minor, patch = [int(x) for x in google.protobuf.__version__.split('.')[:3]]
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    major,
    minor,
    patch,
    '',
    'lawgenesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10lawgenesis.proto\x12\x1borg.apache.dubbo.sample.tri\"0\n\x04\x41uth\x12\x0c\n\x04\x41UTY\x18\x01 \x01(\t\x12\x0c\n\x04\x41\x43ID\x18\x02 \x01(\t\x12\x0c\n\x04\x41\x43KY\x18\x03 \x01(\t\"\x9f\x03\n\x08\x42\x61seData\x12\x0b\n\x03VER\x18\x01 \x01(\t\x12\x0c\n\x04TRID\x18\x02 \x01(\t\x12\x0c\n\x04TRST\x18\x03 \x01(\x03\x12\x0c\n\x04\x45XPT\x18\x04 \x01(\x03\x12/\n\x04\x41UTH\x18\x05 \x01(\x0b\x32!.org.apache.dubbo.sample.tri.Auth\x12=\n\x04\x45\x43HO\x18\x06 \x03(\x0b\x32/.org.apache.dubbo.sample.tri.BaseData.ECHOEntry\x12\x0c\n\x04\x43\x42UR\x18\x07 \x01(\t\x12\x0b\n\x03SLA\x18\x08 \x01(\x05\x12\r\n\x05RETRY\x18\t \x01(\x08\x12\r\n\x05\x43\x41\x43HE\x18\n \x01(\x08\x12\x0c\n\x04\x44TYP\x18\x0b \x01(\t\x12\x0c\n\x04\x44\x41TA\x18\x0c \x01(\x0c\x12=\n\x04\x45XIF\x18\r \x03(\x0b\x32/.org.apache.dubbo.sample.tri.BaseData.EXIFEntry\x1a+\n\tECHOEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tEXIFEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"V\n\x11LawgenesisRequest\x12\x33\n\x04\x42\x41\x44\x41\x18\x01 \x01(\x0b\x32%.org.apache.dubbo.sample.tri.BaseData\x12\x0c\n\x04\x44\x41TA\x18\x02 \x01(\x0c\"X\n\x0fLawgenesisReply\x12\x33\n\x04\x42\x41\x44\x41\x18\x01 \x01(\x0b\x32%.org.apache.dubbo.sample.tri.BaseData\x12\x10\n\x08Response\x18\x02 \x01(\x0c\x32{\n\nLawgenesis\x12m\n\rLawgenesisSdk\x12..org.apache.dubbo.sample.tri.LawgenesisRequest\x1a,.org.apache.dubbo.sample.tri.LawgenesisReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lawgenesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASEDATA_ECHOENTRY']._loaded_options = None
  _globals['_BASEDATA_ECHOENTRY']._serialized_options = b'8\001'
  _globals['_BASEDATA_EXIFENTRY']._loaded_options = None
  _globals['_BASEDATA_EXIFENTRY']._serialized_options = b'8\001'
  _globals['_AUTH']._serialized_start=49
  _globals['_AUTH']._serialized_end=97
  _globals['_BASEDATA']._serialized_start=100
  _globals['_BASEDATA']._serialized_end=515
  _globals['_BASEDATA_ECHOENTRY']._serialized_start=427
  _globals['_BASEDATA_ECHOENTRY']._serialized_end=470
  _globals['_BASEDATA_EXIFENTRY']._serialized_start=472
  _globals['_BASEDATA_EXIFENTRY']._serialized_end=515
  _globals['_LAWGENESISREQUEST']._serialized_start=517
  _globals['_LAWGENESISREQUEST']._serialized_end=603
  _globals['_LAWGENESISREPLY']._serialized_start=605
  _globals['_LAWGENESISREPLY']._serialized_end=693
  _globals['_LAWGENESIS']._serialized_start=695
  _globals['_LAWGENESIS']._serialized_end=818
# @@protoc_insertion_point(module_scope)
